### ISSUE TITLE
Forward old links to newer pages

### ISSUE THREAD

**Issue by marehr** [seqan/www.seqan.de#25]
Old links (from the word press website 2015-2020)
* [x] https://www.seqan.de/announcing-seqan3/ -> /release/2019/06/06/seqan-3-0-0-release.html
* [x] seqan.de/some-news/ -> for example: /release/2019/06/06/seqan-3-0-0-release.html 
* [x] publications/20**/ -> publications
* [x] applications/ -> apps/
* [x] inputoutput/ -> input-and-output/

Oldold links (before word press ????-2015)
* [ ]  -> ...

Should we do something with the old doku at: https://seqan.readthedocs.io/en/master/ ?
This is the first result for "SeqAn docs" on google.

**Comment by marehr** [comment]
Nice! What is with the other apps? We haven't finished porting, did you list all the apPs?

_Originally posted by @marehr in https://github.com/seqan/www.seqan.de/issues/45#issuecomment-804156100_

**Comment by simonsasse** [comment]
I described what to do when porting over a new app in the corresponding issue, so that everyone who ports an app can do the linking himself/herself. I guess I will do most of the porting anyways so I can keep track of that ! :)
