### ISSUE TITLE
Social icons not showing

### ISSUE THREAD

**Issue by eseiler** [seqan/www.seqan.de#40]
On https://www.seqan.de/people/ the icons for "Get in touch" are not showing.
It works when I build locally, but does not on vercel or the live website.

Browser console says
`/assets/minima-social-icons.svg#github:1 Failed to load resource: the server responded with a status of 500 ()`

**Comment by eseiler** [comment]
Nevermind, my adblocker is filtering `-social-cons.`.
That's a bit annoying :)

**Comment by marehr** [comment]
Yeah we should, as they aren't intrusive and no ads :)
