### ISSUE TITLE
Highlight/Add SeqAn3-based apps

### ISSUE THREAD

**Issue by eseiler** [seqan/www.seqan.de#67]
* [ ] Add apps that are built upon SeqAn3
* [x] Mark them somehow, i.e. SeqAn2-Apps vs. SeqAn3-Apps

I can think of:
* [x] Raptor: https://github.com/seqan/raptor
* [x] Chopper: https://github.com/seqan/chopper
* [x] iGenVar: https://github.com/seqan/iGenVar
* [x] Needle: https://github.com/MitraDarja/needle (move to seqan?) Already on Website.
* [x] Mars: https://github.com/seqan/mars
* [ ] Vaquita LR (seqan2 or 3 ?)

**Comment by simonsasse** [comment]
Are all other apps based on Seqan2 or are there some still using seqan1 ?

**Comment by eseiler** [comment]
Official ones should all be at least SeqAn2.
third-party will probably be a few that use(d) SeqAn1, but we can also just not mark third-party for now - which kinda makes sense since we do not / can not track and update third-part apps
