### ISSUE TITLE
Port rabema

### ISSUE THREAD

**Issue by eseiler** [seqan/www.seqan.de#74]
We might have missed rabema in #8 

https://github.com/seqan/seqan/tree/develop/apps/rabema

The readme links to https://seqan.de/projects/rabema.html

**The rabema website also contained the manual**

Rabema was not on the old website:
https://marehr.github.io/old.seqan.de/applications/index.html

But it was on the older website:
https://web.archive.org/web/20141113031730/http://www.seqan.de/projects/rabema/

**Comment by simonsasse** [comment]
Here is a list of all applications present on the old old website but not on the old and not on the current website:
ALF, Breakpoint Calculator, DFI, Rabema, Insegt, PISAtoolbox, NGS Rai, SeqCons, SnpStore, SplazerS.

**Comment by eseiler** [comment]
> I created this list based on the make file from the respective repositories of the apps.

I'm confused what you mean with `not seqan2` and `seqan2`. All these apps use seqan2.
Did you perhaps look at the `SEQAN_APP_VERSION`? This is the version of the app, not the library.

**Comment by simonsasse** [comment]
Indeed I looked at the 'SEQAN_APP_VERSION' 
I'll port some more apps.
